version: '3'
services:
  app:
    image: watchtower-backend
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
      - database
      - redis
    working_dir: /var/www
    volumes:
      - ../..:/var/www
      - app:/var/www
    ports:
      - '8000:8000'
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"
      - "DB_CONNECTION=pgsql"
      - "DB_DATABASE=watchtower"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=postgres"
    depends_on:
      - database
      - redis

  database:
    image: postgres:9.6
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: watchtower
    expose:
      - '5432'
    ports:
      - '5433:5432'

  redis:
    image: redis:4.0
    ports:
      - "6382:6379"

volumes:
  app:
  dbdata:
